---
title: "R Notebook"
output: html_notebook
---


1. Conociendo los datos

```{r}

#1.1. Cargue el paquete tidyverse.

library(tidyverse)

#1.2. Lea el archivo deaths_handwashing.csv usando read_csv y asígnelo a la variable yearly

yearly <- read_csv('deaths_handwashing.csv')

#1.3. Imprima la variable yearly.

view(yearly)

```

2. El alarmante número de muertes

```{r}

#2.1. Use mutate para agregar la columna proportion_deaths a yearly, esta nueva columna se calculará como la proporción de muertes por número de nacimientos.

library(scales)

yearly <- yearly %>%
  mutate(proportion_deaths =  deaths / births) %>%
  mutate(proportion_deaths_percent =  label_percent()(deaths / births))

#2.2. Imprima yearly

view(yearly)

```

3. Muerte en las clínicas


```{r}

#3.1. Utilice ggplot para hacer una gráfica lineal de proportion_deaths por año (columna year) con un línea por clínica.

ggplot(yearly, aes(x = year, y = proportion_deaths, group = clinic)) +
  geom_line(aes(linetype = clinic))

#3.2. Las líneas deben tener colores distintos.

ggplot(yearly, aes(x = year, y = proportion_deaths, color = clinic)) +
  geom_line()

```

4. Comienza el lavado de manos


```{r}

#4.1. Cargue leos datos mensuales de la Clínica 1 para ver si el lavado de manos tuvo algún efecto, para esto lea el archivo deaths_clinic_1.csv y asígnelo a la variable monthly.

monthly <- read_csv('deaths_clinic_1.csv')
view(monthly)

#4.2. Agregue la columna proportion_deaths a monthly, esta nueva columna se calculará como la proporción de muertes por número de nacimientos.

monthly <- monthly %>%
  mutate(proportion_deaths = deaths / births) %>%
  mutate(proportion_deaths_percent = label_percent()(deaths / births))


#4,3, Imprima las primeras filas de monthly usando la función head().

head(monthly)

```

5. El efecto del lavado de manos

```{r}

#5.1. Haga una gráfica lineal de proportion_deaths por fecha para el data frame monthly usando ggplot.

ggplot(monthly, aes(x = date, y = proportion_deaths)) +
  geom_line() 


#5.2. Utilice la función labs para dar al eje x y al eje y una estética a las etiquetas.

ggplot(monthly, aes(x = date, y = proportion_deaths)) +
  geom_line() + labs(title = "Linea de tiempo de proporción de muertes", y = 'Proporción de Muertes', x = 'Fecha')

```

6. Los resultados del lavado de manos


```{r}

#6.1. Agregue una columna TRUE/FALSE a monthly llamado handwashing_started, que será TRUE a partir del año en que se impuso el lavado de manos.

monthly <- monthly %>%
  mutate(handwashing_started = date >= as.Date('1847-01-01'))
monthly

#6.2. Haga una gráfica lineal de proportion_deaths por fecha para el data frame monthly usando ggplot. Haga que el color de la línea dependa de handwashing_started.

ggplot(monthly, aes(x = date, y = proportion_deaths, color = handwashing_started)) +
  geom_line()

#6.3. Utilice la función labs para dar al eje x y al eje y una estética a las etiquetas.

ggplot(monthly, aes(x = date, y = proportion_deaths, color = handwashing_started)) +
  geom_line() + labs(title = "Linea de tiempo de proporción de muertes", y = 'Proporción de Muertes', x = 'Fecha', subtitle = '¿Aplicaban lavado de mano?')

```

7. ¿Más lavado de manos, menos muertes?

```{r}

#7.1. Utilice group_by y summarise para calcular el promedio de proportion_deaths antes y después de que se impusiera el lavado de manos.

monthly %>%
  group_by(handwashing_started) %>%
  summarize(mean_proportion_deaths = median(proportion_deaths))

#7.2. Asigne el resultado en la variable month_summary e imprímala.

month_summary <- monthly %>%
  group_by(handwashing_started) %>%
  summarize(mean_proportion_deaths = median(proportion_deaths))

#7.3. El data frame resultante debería verse como el siguiente:

month_summary %>%
  mutate(mean_proportion_deaths_perecent = label_percent()(mean_proportion_deaths))

view(month_summary)

```



